### ISSUE TITLE
CLI install command have troubles with config.toml which is very minimal

### ISSUE THREAD

**Issue by jumski** [pgflow-dev/pgflow#143]
Then config is minimal and does not have [db] section, like the one below, the install command messess it up

```toml
project_id = "xxxxxxxxxxx"

[auth]
enabled = true
site_url = "https://siteurl.com"
additional_redirect_urls = ["http://127.0.0.1:8080", "https://127.0.0.1:8080", "http://localhost:8080", "https://localhost:8080"]

[auth.external.github]
enabled = true
client_id = "env(GITHUB_OAUTH_CLIENT_ID)"
secret = "env(GITHUB_OAUTH_CLIENT_SECRET)"
redirect_uri = "http://localhost:54321/auth/v1/callback"
``` 

After running install, we end up with this:

![Image](https://github.com/user-attachments/assets/91172143-827a-45bf-80f5-3493c2f33801)
